#!/bin/bash

DIRS=(
    "$HOME/Desktop/homelab"
    "$HOME/Desktop/Projects"
    "$HOME"
    "$HOME/.config"
    "$HOME/.dotfiles"
    "$HOME/.dotfiles/.config"
    "$HOME/Documents/"
)

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find "${DIRS[@]}" -maxdepth 1 -type d -or -type l \
        | sed "s|^$HOME/||"\
        | fzf)
    [[ $selected ]] && selected="$HOME/$selected"
fi

[[ ! $selected ]] && exit 0


selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t "$selected_name"; then
    tmux new-session -ds "$selected_name" -c "$selected" -n 'Shell'
    tmux new-window -t "$selected_name:2" -c "$selected" -n 'Writing' bob run nightly .
    tmux new-window -t "$selected_name:3" -c "$selected" -n 'Serve'
    tmux select-window -t "$selected_name:2"
fi

tmux switch-client -t "$selected_name"

